name: assignment-test
on: 
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:unit-test
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v4
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
                
    # disabled full-test becouse i run out of storage space on my vm :(
    # full-test:
    #     container: cuaesd/aesd-autotest:assignment3
    #     runs-on: self-hosted
    #     steps:
    #       - uses: actions/checkout@v2
    #       - name: Checkout submodules
    #         run : git submodule update --init --recursive
    #       - name: Run full test
    #         run: ./full-test.sh
